name: Bitbucket Sync

on:
  push:
    branches:
      - master
      - main
      - development

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: zent-contrib/sync-git-branch@v1.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-branch: main
          destination-repo: "git@bitbucket.org:nschakravarthymm/github-synced.git"